[project]
name = "cartpole-custom-agent"
version = "0.1.0"
description = "Re-create Cartpole with a NN"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.0",
    "numpy>=2.3.2",
    "pygame>=2.6.1",
    "stable-baselines3>=2.7.0",
    "torch>=2.8.0",
]
